apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: my-service-account@dark-sensor-386805.iam.gserviceaccount.com
    namespace: springdemo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
