apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-deployment
  labels:
    app: currency
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - name: static-site1
        image: us-central1-docker.pkg.dev/dark-sensor-386805/samples/static-site1:1.0
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m