apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: container-deploy-rolebinding
  namespace: springdemo
subjects:
- kind: User
  name: my-service-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: container-deploy-role
  apiGroup: rbac.authorization.k8s.io