apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: container-deploy-role
  namespace: springdemo
rules:
- apiGroups:
  - "" # core API group
  resources:
  - pods
  - pods/exec
  - pods/log
  verbs:
  - create
  - get
  - list
  - watch
  - delete
